#!/usr/bin/env node
/**
 * apply-theme.mjs — Apply a Site Factory theme pack to brand-palette + surfaces.
 *
 * Usage:
 *   npm run theme:apply -- studio-soft
 *   npm run theme:apply -- product-dark /path/to/clone
 *   npm run theme:apply -- default
 *
 * Packs: references/themes/<id>.json
 * Docs: docs/features/THEME-PACKS.md
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");

const themeId = process.argv[2];
if (!themeId) {
  console.error("Usage: npm run theme:apply -- <theme-id> [projectDir]");
  console.error("  Themes: default | product-dark | studio-soft | editorial-ink");
  process.exit(1);
}

const projectDir = process.argv[3]
  ? path.resolve(process.argv[3])
  : process.cwd();

const packPath = path.join(root, "references/themes", `${themeId}.json`);
const packPathLocal = path.join(projectDir, "references/themes", `${themeId}.json`);
const resolvedPack = fs.existsSync(packPathLocal)
  ? packPathLocal
  : fs.existsSync(packPath)
    ? packPath
    : null;

if (!resolvedPack) {
  console.error(`✗ Theme pack not found: ${themeId}`);
  process.exit(1);
}

const pack = JSON.parse(fs.readFileSync(resolvedPack, "utf8"));

function patchBrandPalette(css, brand) {
  let out = css;
  out = out.replace(/(--brand-hue:\s*)[0-9.]+/, `$1${brand.hue}`);
  // First chroma in :root only — replace both carefully
  const rootMatch = out.match(/:root\s*\{[\s\S]*?\n\}/);
  if (rootMatch) {
    let root = rootMatch[0];
    root = root.replace(/(--brand-chroma:\s*)[0-9.]+/, `$1${brand.chroma}`);
    root = root.replace(/(--brand-lightness:\s*)[0-9.]+/, `$1${brand.lightness}`);
    out = out.replace(rootMatch[0], root);
  }
  const darkMatch = out.match(/\.dark\s*\{[\s\S]*?\n\}/);
  if (darkMatch) {
    let dark = darkMatch[0];
    dark = dark.replace(/(--brand-lightness:\s*)[0-9.]+/, `$1${brand.darkLightness}`);
    dark = dark.replace(/(--brand-chroma:\s*)[0-9.]+/, `$1${brand.darkChroma}`);
    out = out.replace(darkMatch[0], dark);
  }
  return out;
}

function surfaceBlock(selector, surfaces, radius, headingStack) {
  if (!surfaces && !radius && !headingStack) return "";
  const lines = [];
  lines.push(`${selector} {`);
  if (radius) lines.push(`  --radius: ${radius};`);
  if (headingStack) {
    lines.push(`  --theme-font-heading: ${headingStack};`);
  }
  if (surfaces) {
    if (surfaces.background) lines.push(`  --background: ${surfaces.background};`);
    if (surfaces.foreground) lines.push(`  --foreground: ${surfaces.foreground};`);
    if (surfaces.card) lines.push(`  --card: ${surfaces.card};`);
    if (surfaces.card) lines.push(`  --card-foreground: ${surfaces.foreground ?? "inherit"};`);
    if (surfaces.muted) lines.push(`  --muted: ${surfaces.muted};`);
    if (surfaces.mutedForeground) {
      lines.push(`  --muted-foreground: ${surfaces.mutedForeground};`);
    }
    if (surfaces.border) lines.push(`  --border: ${surfaces.border};`);
    if (surfaces.border) lines.push(`  --input: ${surfaces.border};`);
    if (surfaces.secondary) lines.push(`  --secondary: ${surfaces.secondary};`);
    if (surfaces.secondary && surfaces.foreground) {
      lines.push(`  --secondary-foreground: ${surfaces.foreground};`);
    }
    if (surfaces.card) lines.push(`  --popover: ${surfaces.card};`);
    if (surfaces.foreground) {
      lines.push(`  --popover-foreground: ${surfaces.foreground};`);
    }
  }
  lines.push(`}`);
  return lines.join("\n");
}

function buildThemePackCss(pack) {
  const parts = [
    "/*",
    " * Theme pack surface overrides — generated by `npm run theme:apply`.",
    " * THEME_PACK_BEGIN",
    ` * id: ${pack.id}`,
    ` * label: ${pack.label ?? pack.id}`,
    " * THEME_PACK_END",
    " */",
    "",
  ];

  const headingStack = pack.fonts?.headingStack ?? null;
  const radius = pack.radius ?? null;

  if (pack.surfaces || radius || headingStack) {
    parts.push(surfaceBlock(":root", pack.surfaces, radius, headingStack));
    parts.push("");
  }

  if (pack.darkSurfaces || radius || headingStack) {
    parts.push(
      surfaceBlock(".dark", pack.darkSurfaces ?? pack.surfaces, radius, headingStack),
    );
    parts.push("");
  }

  if (headingStack) {
    parts.push("h1, h2, h3, .font-heading {");
    parts.push("  font-family: var(--theme-font-heading), var(--font-geist-sans), ui-sans-serif, system-ui, sans-serif;");
    parts.push("}");
    parts.push("");
  }

  if (pack.forceSurfaceMode === "dark") {
    parts.push("/* product-dark: light scheme still uses dark surfaces from :root overrides */");
    parts.push("");
  }

  return parts.join("\n");
}

function writeAppliedThemeTs(pack) {
  const scheme = pack.defaultColorScheme ?? "system";
  return `/**
 * Active theme pack metadata — rewritten by \`npm run theme:apply -- <id>\`.
 * ThemeProvider reads defaultColorScheme; do not edit by hand in clones
 * unless you know you are leaving the apply script.
 */
export const appliedTheme = {
  id: ${JSON.stringify(pack.id)},
  label: ${JSON.stringify(pack.label ?? pack.id)},
  defaultColorScheme: ${JSON.stringify(scheme)} as "system" | "light" | "dark",
} as const;

export type AppliedThemeId = typeof appliedTheme.id;
`;
}

// --- apply ---
const palettePath = path.join(projectDir, "src/lib/theme/brand-palette.css");
if (!fs.existsSync(palettePath)) {
  console.error(`✗ Missing ${palettePath}`);
  process.exit(1);
}

let palette = fs.readFileSync(palettePath, "utf8");
palette = patchBrandPalette(palette, pack.brand);
fs.writeFileSync(palettePath, palette);
console.log(`→ Updated brand-palette.css (hue=${pack.brand.hue}, chroma=${pack.brand.chroma})`);

const packCssPath = path.join(projectDir, "src/lib/theme/theme-pack.css");
fs.mkdirSync(path.dirname(packCssPath), { recursive: true });
fs.writeFileSync(packCssPath, buildThemePackCss(pack));
console.log(`→ Wrote theme-pack.css (${pack.id})`);

const appliedPath = path.join(projectDir, "src/lib/theme/applied-theme.ts");
fs.writeFileSync(appliedPath, writeAppliedThemeTs(pack));
console.log(`→ Wrote applied-theme.ts (defaultColorScheme=${pack.defaultColorScheme ?? "system"})`);

const siteConfigPath = path.join(projectDir, "src/lib/site-config.ts");
if (fs.existsSync(siteConfigPath)) {
  let src = fs.readFileSync(siteConfigPath, "utf8");
  src = src.replace(
    /(hue:\s*)[0-9.]+/,
    `$1${pack.brand.hue}`,
  );
  src = src.replace(
    /(chroma:\s*)[0-9.]+/,
    `$1${pack.brand.chroma}`,
  );
  fs.writeFileSync(siteConfigPath, src);
  console.log("→ Updated site-config brandTokens");
}

const siteJsonPath = path.join(projectDir, "content/site.json");
if (fs.existsSync(siteJsonPath)) {
  const site = JSON.parse(fs.readFileSync(siteJsonPath, "utf8"));
  site.theme = pack.id;
  fs.writeFileSync(siteJsonPath, `${JSON.stringify(site, null, 2)}\n`);
  console.log("→ Updated content/site.json theme");
}

const appliedMeta = {
  appliedAt: new Date().toISOString(),
  theme: pack.id,
  pack: path.relative(projectDir, resolvedPack),
  antiSlop: pack.antiSlop ?? [],
};
fs.mkdirSync(path.join(projectDir, "content"), { recursive: true });
fs.writeFileSync(
  path.join(projectDir, "content/theme-applied.json"),
  `${JSON.stringify(appliedMeta, null, 2)}\n`,
);

console.log(`✓ Theme applied: ${pack.id} (${pack.label ?? pack.id})`);
if (Array.isArray(pack.antiSlop) && pack.antiSlop.length) {
  console.log("  Anti-slop:");
  for (const rule of pack.antiSlop) console.log(`  - ${rule}`);
}
